// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyPhongMach.Data;

#nullable disable

namespace QuanLyPhongMach.Migrations
{
    [DbContext(typeof(PhongMachDbContext))]
    [Migration("20260321145913_ThemTrangThaiChoLichKham")]
    partial class ThemTrangThaiChoLichKham
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.BacSi", b =>
                {
                    b.Property<int>("MaBS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBS"));

                    b.Property<string>("ChuyenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaTK")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenBS")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaBS");

                    b.HasIndex("MaTK");

                    b.ToTable("BACSI");
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.HoaDon", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHD"));

                    b.Property<int>("MaPK")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHD");

                    b.HasIndex("MaPK")
                        .IsUnique();

                    b.ToTable("HOADON");
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MaTK")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKH");

                    b.HasIndex("MaTK");

                    b.ToTable("KHACHHANG");
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.LichKham", b =>
                {
                    b.Property<int>("MaLichKham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichKham"));

                    b.Property<TimeSpan>("GioKham")
                        .HasColumnType("time");

                    b.Property<int>("MaBS")
                        .HasColumnType("int");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKham")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLichKham");

                    b.HasIndex("MaBS");

                    b.HasIndex("MaKH");

                    b.ToTable("LICHKHAM");
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.NhanVien", b =>
                {
                    b.Property<int>("MaNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNV"));

                    b.Property<int>("MaTK")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaTK");

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.NhatKyHeThong", b =>
                {
                    b.Property<int>("MaLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLog"));

                    b.Property<string>("BangTacDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaDoiTuong")
                        .HasColumnType("int");

                    b.Property<int>("MaTK")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLog");

                    b.HasIndex("MaTK");

                    b.ToTable("NHATKYHETHONG");
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.PhieuKham", b =>
                {
                    b.Property<int>("MaPK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPK"));

                    b.Property<string>("ChanDoan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoiDan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaLichKham")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.HasKey("MaPK");

                    b.HasIndex("MaLichKham")
                        .IsUnique();

                    b.ToTable("PHIEUKHAM");
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("MaTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTK"));

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTK");

                    b.ToTable("TAIKHOAN");
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.BacSi", b =>
                {
                    b.HasOne("QuanLyPhongMach.Data.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.HoaDon", b =>
                {
                    b.HasOne("QuanLyPhongMach.Data.Entities.PhieuKham", "PhieuKham")
                        .WithOne("HoaDon")
                        .HasForeignKey("QuanLyPhongMach.Data.Entities.HoaDon", "MaPK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuKham");
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.KhachHang", b =>
                {
                    b.HasOne("QuanLyPhongMach.Data.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.LichKham", b =>
                {
                    b.HasOne("QuanLyPhongMach.Data.Entities.BacSi", "BacSi")
                        .WithMany("LichKhams")
                        .HasForeignKey("MaBS")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyPhongMach.Data.Entities.KhachHang", "KhachHang")
                        .WithMany("LichKhams")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.NhanVien", b =>
                {
                    b.HasOne("QuanLyPhongMach.Data.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.NhatKyHeThong", b =>
                {
                    b.HasOne("QuanLyPhongMach.Data.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("MaTK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.PhieuKham", b =>
                {
                    b.HasOne("QuanLyPhongMach.Data.Entities.LichKham", "LichKham")
                        .WithOne("PhieuKham")
                        .HasForeignKey("QuanLyPhongMach.Data.Entities.PhieuKham", "MaLichKham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichKham");
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.BacSi", b =>
                {
                    b.Navigation("LichKhams");
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.KhachHang", b =>
                {
                    b.Navigation("LichKhams");
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.LichKham", b =>
                {
                    b.Navigation("PhieuKham")
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyPhongMach.Data.Entities.PhieuKham", b =>
                {
                    b.Navigation("HoaDon")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
